# File: C:\AI\apps\Makehuman\dg_face_pipeline\export_maya_arnold_scene.py
"""
Export a MediaPipe face OBJ to a Maya ASCII scene with an Arnold skin shader.

The generated .ma imports a Maya-normalized OBJ on open and references the
source photo through a Maya file texture connected to an aiStandardSurface
baseColor. Maya units are centimeters, so the exporter recenters the mesh at
the origin and scales the face to a sensible real-world head height.
"""
from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path
from typing import Iterable, List, Tuple

import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("export_maya_arnold_scene")

PIPELINE_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = PIPELINE_DIR / "outputs"
EXAMPLES_DIR = PIPELINE_DIR / "examples"
ARNOLD_SUBDIV_TYPES = {
    "none": 0,
    "catclark": 1,
    "linear": 2,
}
DEFAULT_MATERIAL_NAME = "face_photo_mat"


def _maya_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def _chunks(seq: List, size: int) -> Iterable[Tuple[int, List]]:
    for start in range(0, len(seq), size):
        yield start, seq[start:start + size]


def _relative_texture_ref(from_dir: Path, texture: Path) -> str:
    return os.path.relpath(texture.resolve(), start=from_dir.resolve()).replace("\\", "/")


def write_mtl_for_obj(
    out_obj: Path,
    albedo: Path,
    roughness: Path | None = None,
    normal: Path | None = None,
) -> Path:
    mtl = out_obj.with_suffix(".mtl")
    with mtl.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# PBR material generated by DG Face Pipeline\n")
        fh.write(f"newmtl {DEFAULT_MATERIAL_NAME}\n")
        fh.write("Ka 0.000000 0.000000 0.000000\n")
        fh.write("Kd 1.000000 1.000000 1.000000\n")
        fh.write("Ks 0.120000 0.120000 0.120000\n")
        fh.write("Ns 16.000000\n")
        fh.write("illum 2\n")
        fh.write(f"map_Kd {_relative_texture_ref(out_obj.parent, albedo)}\n")
        if roughness is not None:
            fh.write(f"map_Pr {_relative_texture_ref(out_obj.parent, roughness)}\n")
        if normal is not None:
            normal_ref = _relative_texture_ref(out_obj.parent, normal)
            fh.write(f"norm {normal_ref}\n")
            fh.write(f"map_Bump -bm 0.12 {normal_ref}\n")
    return mtl


def load_obj(obj_path: Path) -> tuple[np.ndarray, np.ndarray, List[List[int]], List[List[int]]]:
    verts: List[List[float]] = []
    uvs: List[List[float]] = []
    faces_v: List[List[int]] = []
    faces_uv: List[List[int]] = []
    with obj_path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if parts[0] == "v":
                verts.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "vt":
                uvs.append([float(parts[1]), float(parts[2])])
            elif parts[0] == "f":
                v_idx: List[int] = []
                uv_idx: List[int] = []
                for item in parts[1:]:
                    bits = item.split("/")
                    v_idx.append(int(bits[0]) - 1)
                    uv_idx.append(int(bits[1]) - 1 if len(bits) > 1 and bits[1] else int(bits[0]) - 1)
                faces_v.append(v_idx)
                faces_uv.append(uv_idx)
    if not verts or not faces_v:
        raise ValueError(f"OBJ has no mesh data: {obj_path}")
    return (
        np.asarray(verts, dtype=np.float64),
        np.asarray(uvs, dtype=np.float64) if uvs else np.empty((0, 2), dtype=np.float64),
        faces_v,
        faces_uv,
    )


def normalize_vertices(verts: np.ndarray, height_cm: float) -> np.ndarray:
    centered = verts.copy()
    bbox_min = centered.min(axis=0)
    bbox_max = centered.max(axis=0)
    bbox_center = (bbox_min + bbox_max) / 2.0
    centered -= bbox_center
    height = max(float(bbox_max[1] - bbox_min[1]), 1e-6)
    centered *= height_cm / height
    return centered


def write_normalized_obj(
    src_obj: Path,
    out_obj: Path,
    texture: Path,
    verts: np.ndarray,
    uvs: np.ndarray,
    faces_v: List[List[int]],
    faces_uv: List[List[int]],
    height_cm: float,
    roughness: Path | None = None,
    normal: Path | None = None,
) -> Path:
    out_obj.parent.mkdir(parents=True, exist_ok=True)
    norm_verts = normalize_vertices(verts, height_cm)
    normals = compute_vertex_normals(norm_verts, faces_v)
    mtl = write_mtl_for_obj(out_obj, texture, roughness=roughness, normal=normal)
    with out_obj.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Maya-normalized face mesh exported by DG Face Pipeline\n")
        fh.write(f"# Source OBJ: {src_obj}\n")
        fh.write(f"# Height: {height_cm:.3f} cm, centered at origin\n")
        fh.write(f"mtllib {mtl.name}\n")
        fh.write("g face_mesh\n")
        fh.write(f"usemtl {DEFAULT_MATERIAL_NAME}\n")
        for x, y, z in norm_verts:
            fh.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for u, v in uvs:
            fh.write(f"vt {u:.6f} {v:.6f}\n")
        for x, y, z in normals:
            fh.write(f"vn {x:.6f} {y:.6f} {z:.6f}\n")
        for fv, fuv in zip(faces_v, faces_uv):
            parts = [f"{vi + 1}/{ui + 1}/{vi + 1}" for vi, ui in zip(fv, fuv)]
            fh.write("f " + " ".join(parts) + "\n")
    return out_obj


def compute_vertex_normals(verts: np.ndarray, faces_v: List[List[int]]) -> np.ndarray:
    normals = np.zeros_like(verts)
    for face in faces_v:
        if len(face) < 3:
            continue
        idx = np.asarray(face, dtype=np.int64)
        p0, p1, p2 = verts[idx[0]], verts[idx[1]], verts[idx[2]]
        n = np.cross(p1 - p0, p2 - p0)
        length = float(np.linalg.norm(n))
        if length <= 1e-12:
            continue
        n /= length
        for vi in idx:
            normals[vi] += n
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    normals = np.divide(normals, np.where(lengths == 0.0, 1.0, lengths))
    return normals


def write_mesh(fh, name: str, verts: np.ndarray, uvs: np.ndarray, faces_v: List[List[int]], faces_uv: List[List[int]]) -> None:
    transform = f"{name}_GEO"
    shape = f"{name}_GEOShape"
    fh.write(f'createNode transform -n "{transform}";\n')
    fh.write(f'createNode mesh -n "{shape}" -p "{transform}";\n')
    fh.write('\tsetAttr -k off ".v";\n')
    fh.write('\tsetAttr ".vir" yes;\n')
    fh.write('\tsetAttr ".vif" yes;\n')
    fh.write('\tsetAttr ".uvst[0].uvsn" -type "string" "map1";\n')

    vert_rows = verts.tolist()
    for start, chunk in _chunks(vert_rows, 500):
        end = start + len(chunk) - 1
        fh.write(f'\tsetAttr -s {len(chunk)} ".vt[{start}:{end}]"')
        for x, y, z in chunk:
            fh.write(f" {x:.6f} {y:.6f} {z:.6f}")
        fh.write(";\n")

    if len(uvs):
        uv_rows = uvs.tolist()
        for start, chunk in _chunks(uv_rows, 500):
            end = start + len(chunk) - 1
            fh.write(f'\tsetAttr -s {len(chunk)} ".uvst[0].uvsp[{start}:{end}]" -type "float2"')
            for u, v in chunk:
                fh.write(f" {u:.6f} {v:.6f}")
            fh.write(";\n")

    for start, face_chunk in _chunks(list(range(len(faces_v))), 400):
        end = start + len(face_chunk) - 1
        fh.write(f'\tsetAttr -s {len(face_chunk)} ".fc[{start}:{end}]" -type "polyFaces"\n')
        for face_index in face_chunk:
            fv = faces_v[face_index]
            fuv = faces_uv[face_index] if len(uvs) else fv
            fh.write(f'\t\tf {len(fv)} {" ".join(str(i) for i in fv)}')
            if len(uvs):
                fh.write(f' mu 0 {len(fuv)} {" ".join(str(i) for i in fuv)}')
            fh.write("\n")
        fh.write("\t\t;\n")

    fh.write('\tsetAttr ".cd" -type "dataPolyComponent" Index_Data Edge 0 ;\n')
    fh.write('\tsetAttr ".dcc" -type "string" "Ambient+Diffuse";\n')


def write_texture_file_node(fh, name: str, label: str, texture: Path, color_space: str) -> str:
    file_node = f"{name}_{label}_file"
    place_node = f"{name}_{label}_place2d"
    fh.write(f'createNode file -n "{file_node}";\n')
    fh.write(f'\tsetAttr ".ftn" -type "string" "{_maya_path(texture)}";\n')
    fh.write(f'\tsetAttr ".cs" -type "string" "{color_space}";\n')
    if color_space == "Raw":
        fh.write('\tsetAttr ".ail" yes;\n')
    fh.write(f'createNode place2dTexture -n "{place_node}";\n')
    for src, dst in [
        ("coverage", "coverage"),
        ("translateFrame", "translateFrame"),
        ("rotateFrame", "rotateFrame"),
        ("mirrorU", "mirrorU"),
        ("mirrorV", "mirrorV"),
        ("stagger", "stagger"),
        ("wrapU", "wrapU"),
        ("wrapV", "wrapV"),
        ("repeatUV", "repeatUV"),
        ("offset", "offset"),
        ("rotateUV", "rotateUV"),
        ("noiseUV", "noiseUV"),
        ("vertexUvOne", "vertexUvOne"),
        ("vertexUvTwo", "vertexUvTwo"),
        ("vertexUvThree", "vertexUvThree"),
        ("vertexCameraOne", "vertexCameraOne"),
        ("outUV", "uvCoord"),
        ("outUvFilterSize", "uvFilterSize"),
    ]:
        fh.write(f'connectAttr "{place_node}.{src}" "{file_node}.{dst}";\n')
    return file_node


def write_shader(
    fh,
    name: str,
    albedo: Path,
    roughness: Path | None = None,
    normal: Path | None = None,
) -> None:
    fh.write(f'createNode shadingEngine -n "{name}_skin_SG";\n')
    fh.write('\tsetAttr ".ihi" 0;\n')
    fh.write('\tsetAttr ".ro" yes;\n')
    fh.write('createNode aiStandardSurface -n "{}_skin_aiStandardSurface";\n'.format(name))
    fh.write('\tsetAttr ".base" 0.85;\n')
    fh.write('\tsetAttr ".baseColor" -type "float3" 0.78 0.48 0.38;\n')
    fh.write('\tsetAttr ".specular" 0.35;\n')
    fh.write('\tsetAttr ".specularRoughness" 0.52;\n')
    fh.write('\tsetAttr ".subsurface" 0.18;\n')
    fh.write('\tsetAttr ".subsurfaceColor" -type "float3" 1 0.58 0.42;\n')
    fh.write('\tsetAttr ".subsurfaceRadius" -type "float3" 1 0.35 0.18;\n')
    albedo_node = write_texture_file_node(fh, name, "albedo", albedo, "sRGB")
    fh.write(f'connectAttr "{albedo_node}.outColor" "{name}_skin_aiStandardSurface.baseColor";\n')
    if roughness is not None:
        roughness_node = write_texture_file_node(fh, name, "roughness", roughness, "Raw")
        fh.write(f'connectAttr "{roughness_node}.outColorR" "{name}_skin_aiStandardSurface.specularRoughness";\n')
    if normal is not None:
        normal_node = write_texture_file_node(fh, name, "normal", normal, "Raw")
        fh.write(f'createNode bump2d -n "{name}_normal_bump2d";\n')
        fh.write('\tsetAttr ".bi" 1;\n')
        fh.write('\tsetAttr ".bd" 0.08;\n')
        fh.write('\tsetAttr ".bf" 1.25;\n')
        fh.write(f'connectAttr "{normal_node}.outAlpha" "{name}_normal_bump2d.bumpValue";\n')
        fh.write(f'connectAttr "{name}_normal_bump2d.outNormal" "{name}_skin_aiStandardSurface.normalCamera";\n')
    fh.write(f'connectAttr "{name}_skin_aiStandardSurface.outColor" "{name}_skin_SG.surfaceShader";\n')


def write_camera_and_lights(fh, name: str) -> None:
    fh.write('createNode transform -n "render_cam";\n')
    fh.write('\tsetAttr ".t" -type "double3" 0 2 120;\n')
    fh.write('createNode camera -n "render_camShape" -p "render_cam";\n')
    fh.write('\tsetAttr ".fl" 50;\n')
    fh.write('\tsetAttr ".ncp" 0.1;\n')
    fh.write('\tsetAttr ".fcp" 1000;\n')
    fh.write('createNode transform -n "key_area_light";\n')
    fh.write('\tsetAttr ".t" -type "double3" -45 55 80;\n')
    fh.write('\tsetAttr ".r" -type "double3" -30 -20 0;\n')
    fh.write('createNode aiAreaLight -n "key_area_lightShape" -p "key_area_light";\n')
    fh.write('\tsetAttr ".intensity" 650;\n')
    fh.write('\tsetAttr ".exposure" 0;\n')
    fh.write('\tsetAttr ".aiSamples" 3;\n')
    fh.write('createNode transform -n "fill_area_light";\n')
    fh.write('\tsetAttr ".t" -type "double3" 55 35 75;\n')
    fh.write('\tsetAttr ".r" -type "double3" -25 25 0;\n')
    fh.write('createNode aiAreaLight -n "fill_area_lightShape" -p "fill_area_light";\n')
    fh.write('\tsetAttr ".intensity" 130;\n')
    fh.write('\tsetAttr ".aiSamples" 2;\n')
    fh.write('setAttr "defaultRenderGlobals.ren" -type "string" "arnold";\n')


def write_obj_import(
    fh,
    name: str,
    obj: Path,
    arnold_subdiv_type: str,
    arnold_subdiv_iterations: int,
    layout: str,
    front_rotate_y: float,
) -> None:
    obj_path = _maya_path(obj)
    subdiv_type_id = ARNOLD_SUBDIV_TYPES[arnold_subdiv_type]
    import_namespace = f"dg_{name}_import"
    fh.write('if (!`pluginInfo -q -loaded "objExport"`) loadPlugin -quiet "objExport";\n')
    fh.write(f'if (`namespace -exists "{import_namespace}"`) namespace -removeNamespace "{import_namespace}" -mergeNamespaceWithRoot;\n')
    fh.write(f'namespace -add "{import_namespace}";\n')
    fh.write(f'file -import -type "OBJ" -ignoreVersion -ra true -mergeNamespacesOnClash false -namespace "{import_namespace}" "{obj_path}";\n')
    fh.write(f'string $dgFaceShapes[] = `ls -type "mesh" "{import_namespace}:*"`;\n')
    fh.write('for ($shape in $dgFaceShapes) {\n')
    fh.write(f'\tsets -e -forceElement "{name}_skin_SG" $shape;\n')
    fh.write('\tcatch(`setAttr ($shape + ".displaySmoothMesh") 2`);\n')
    fh.write('\tcatch(`setAttr ($shape + ".smoothLevel") 1`);\n')
    fh.write(f'\tcatch(`setAttr ($shape + ".renderSmoothLevel") {max(0, arnold_subdiv_iterations)}`);\n')
    fh.write(f'\tcatch(`setAttr ($shape + ".aiSubdivType") {subdiv_type_id}`);\n')
    fh.write(f'\tcatch(`setAttr ($shape + ".aiSubdivIterations") {max(0, arnold_subdiv_iterations)}`);\n')
    fh.write('\tcatch(`setAttr ($shape + ".aiSubdivSmoothDerivs") 1`);\n')
    fh.write('}\n')
    fh.write('string $dgFaceTransforms[] = `listRelatives -p $dgFaceShapes`;\n')
    fh.write('if (size($dgFaceTransforms) > 0) {\n')
    fh.write(f'\tstring $main = `rename $dgFaceTransforms[0] "{name}_GEO"`;\n')
    fh.write('\tselect -r $main;\n')
    fh.write('\tcatch(`polySoftEdge -a 180 -ch 1`);\n')
    fh.write('\tsetAttr ($main + ".translateX") 0;\n')
    fh.write(f'\tsetAttr ($main + ".rotateY") {front_rotate_y:.6f};\n')
    if layout == "three":
        fh.write(f'\tstring $left[] = `duplicate -rr -n "{name}_GEO_left" $main`;\n')
        fh.write(f'\tstring $right[] = `duplicate -rr -n "{name}_GEO_right" $main`;\n')
        fh.write('\tsetAttr ($left[0] + ".translateX") -24;\n')
        fh.write(f'\tsetAttr ($left[0] + ".rotateY") {front_rotate_y + 24.0:.6f};\n')
        fh.write('\tsetAttr ($right[0] + ".translateX") 24;\n')
        fh.write(f'\tsetAttr ($right[0] + ".rotateY") {front_rotate_y - 24.0:.6f};\n')
    fh.write('}\n')
    fh.write(f'select -r "{name}_GEO";\n')


def export_scene(
    obj: Path,
    texture: Path,
    out_scene: Path,
    name: str,
    height_cm: float,
    arnold_subdiv_type: str,
    arnold_subdiv_iterations: int,
    layout: str,
    front_rotate_y: float,
    roughness: Path | None = None,
    normal: Path | None = None,
) -> Path:
    verts, uvs, faces_v, faces_uv = load_obj(obj)
    maya_obj = out_scene.with_name(f"{name}_face_mesh_maya_cm.obj")
    write_normalized_obj(
        obj,
        maya_obj,
        texture,
        verts,
        uvs,
        faces_v,
        faces_uv,
        height_cm,
        roughness=roughness,
        normal=normal,
    )
    out_scene.parent.mkdir(parents=True, exist_ok=True)
    with out_scene.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("//Maya ASCII 2024 scene\n")
        fh.write(f"//Generated from: {_maya_path(maya_obj)}\n")
        fh.write(f"//Texture: {_maya_path(texture)}\n")
        if roughness is not None:
            fh.write(f"//Roughness: {_maya_path(roughness)}\n")
        if normal is not None:
            fh.write(f"//Normal: {_maya_path(normal)}\n")
        fh.write(f"//Mesh centered at world origin, height {height_cm:.3f} cm\n")
        fh.write(f"//Arnold subdivision: {arnold_subdiv_type}, iterations {max(0, arnold_subdiv_iterations)}\n")
        fh.write(f"//Layout: {layout}\n")
        fh.write(f"//Front yaw correction: rotateY {front_rotate_y:.3f}\n")
        fh.write('requires maya "2024";\n')
        fh.write('requires "mtoa" "5.0";\n')
        fh.write('currentUnit -l centimeter -a degree -t film;\n')
        fh.write('fileInfo "application" "DG Face Pipeline";\n')
        write_shader(fh, name, texture, roughness=roughness, normal=normal)
        write_camera_and_lights(fh, name)
        write_obj_import(
            fh,
            name,
            maya_obj,
            arnold_subdiv_type,
            arnold_subdiv_iterations,
            layout,
            front_rotate_y,
        )
    log.info(
        "Wrote Maya Arnold loader scene: %s (%d verts, %d UVs, %d faces, %.2f cm high, %s x%d)",
        out_scene, len(verts), len(uvs), len(faces_v), height_cm,
        arnold_subdiv_type, max(0, arnold_subdiv_iterations),
    )
    return out_scene


def default_character_paths(subject: str) -> tuple[Path, Path, Path]:
    data_root = OUTPUTS_DIR / "characters" / subject / "data"
    renders_root = OUTPUTS_DIR / "characters" / subject / "maya"
    obj = data_root / f"{subject}_face_mesh.obj"
    texture = EXAMPLES_DIR / subject / "ref.png"
    out = renders_root / f"{subject}_arnold_skin.ma"
    return obj, texture, out


def default_texture_maps(subject: str) -> tuple[Path | None, Path | None, Path | None]:
    root = OUTPUTS_DIR / "characters" / subject / "textures"
    albedo = root / f"{subject}_albedo.jpg"
    roughness = root / f"{subject}_roughness.jpg"
    normal = root / f"{subject}_normal.jpg"
    return (
        albedo if albedo.exists() else None,
        roughness if roughness.exists() else None,
        normal if normal.exists() else None,
    )


def parse_args(argv: List[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Export a character face mesh to Maya Arnold .ma.")
    p.add_argument("--subject", default="winona")
    p.add_argument("--obj", type=Path, default=None)
    p.add_argument("--texture", type=Path, default=None)
    p.add_argument("--albedo", type=Path, default=None)
    p.add_argument("--roughness", type=Path, default=None)
    p.add_argument("--normal", type=Path, default=None)
    p.add_argument("--out", type=Path, default=None)
    p.add_argument(
        "--height-cm",
        type=float,
        default=22.0,
        help="Normalize the imported face mesh to this Y height in Maya centimeters.",
    )
    p.add_argument(
        "--arnold-subdiv-type",
        choices=sorted(ARNOLD_SUBDIV_TYPES),
        default="catclark",
        help="Arnold subdivision type to request on the imported mesh.",
    )
    p.add_argument(
        "--arnold-subdiv-iterations",
        type=int,
        default=1,
        help="Arnold render subdivision iterations and Maya render smooth level.",
    )
    p.add_argument(
        "--layout",
        choices=["single", "three"],
        default="three",
        help="Scene layout to create after importing the normalized OBJ.",
    )
    p.add_argument(
        "--front-rotate-y",
        type=float,
        default=-24.0,
        help="Yaw correction in degrees for the center mesh to face the render camera.",
    )
    return p.parse_args(argv)


def main(argv: List[str] | None = None) -> int:
    args = parse_args(argv)
    default_obj, default_texture, default_out = default_character_paths(args.subject)
    default_albedo, default_roughness, default_normal = default_texture_maps(args.subject)
    obj = args.obj or default_obj
    texture = args.albedo or args.texture or default_albedo or default_texture
    roughness = args.roughness or default_roughness
    normal = args.normal or default_normal
    out = args.out or default_out
    try:
        export_scene(
            obj,
            texture,
            out,
            args.subject,
            args.height_cm,
            args.arnold_subdiv_type,
            args.arnold_subdiv_iterations,
            args.layout,
            args.front_rotate_y,
            roughness,
            normal,
        )
    except (FileNotFoundError, ValueError, IOError) as exc:
        log.error("Export failed: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
