"""
Generate first-pass JPG texture maps for a character.

These maps are look-dev helpers from a single source photo. The albedo is the
photo converted to JPG, the roughness is a conservative grayscale estimate, and
the normal is a shallow luminance-derived tangent normal. Replace them later
with proper baked/painted maps when the MakeHuman refit exists.
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import List

import cv2
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("generate_texture_maps")

PIPELINE_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = PIPELINE_DIR / "outputs"
EXAMPLES_DIR = PIPELINE_DIR / "examples"
MATERIAL_NAME = "face_photo_mat"


def write_jpg(path: Path, image: np.ndarray, quality: int = 95) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ok = cv2.imwrite(str(path), image, [int(cv2.IMWRITE_JPEG_QUALITY), int(quality)])
    if not ok:
        raise IOError(f"OpenCV could not write {path}")


def build_maps(photo: Path, out_dir: Path, subject: str) -> tuple[Path, Path, Path]:
    img = cv2.imread(str(photo), cv2.IMREAD_COLOR)
    if img is None:
        raise IOError(f"OpenCV could not decode {photo}")

    albedo = out_dir / f"{subject}_albedo.jpg"
    roughness = out_dir / f"{subject}_roughness.jpg"
    normal = out_dir / f"{subject}_normal.jpg"

    write_jpg(albedo, img, quality=95)

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    value = hsv[:, :, 2].astype(np.float32)
    sat = hsv[:, :, 1].astype(np.float32)
    spec_likelihood = np.clip((value - 180.0) / 75.0, 0.0, 1.0) * np.clip((110.0 - sat) / 110.0, 0.0, 1.0)
    rough = 190.0 - spec_likelihood * 65.0
    rough = cv2.GaussianBlur(rough, (0, 0), 5.0)
    rough_img = np.clip(rough, 0, 255).astype(np.uint8)
    write_jpg(roughness, rough_img, quality=95)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY).astype(np.float32) / 255.0
    gray = cv2.GaussianBlur(gray, (0, 0), 2.0)
    dx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    dy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    strength = 0.08
    nx = -dx * strength
    ny = dy * strength
    nz = np.ones_like(gray)
    length = np.sqrt(nx * nx + ny * ny + nz * nz)
    normal_bgr = np.dstack((
        ((nz / length) * 0.5 + 0.5) * 255.0,
        ((ny / length) * 0.5 + 0.5) * 255.0,
        ((nx / length) * 0.5 + 0.5) * 255.0,
    ))
    write_jpg(normal, np.clip(normal_bgr, 0, 255).astype(np.uint8), quality=95)

    return albedo, roughness, normal


def ensure_obj_material(obj: Path, mtl_name: str) -> None:
    if not obj.exists():
        return
    lines = obj.read_text(encoding="utf-8").splitlines()
    has_mtllib = any(line.startswith("mtllib ") for line in lines)
    has_usemtl = any(line.startswith("usemtl ") for line in lines)
    out: list[str] = []
    inserted_mtllib = False
    inserted_usemtl = False
    for line in lines:
        if line.startswith("mtllib "):
            if not inserted_mtllib:
                out.append(f"mtllib {mtl_name}")
                inserted_mtllib = True
            continue
        out.append(line)
        if not has_mtllib and not inserted_mtllib and line.startswith("#"):
            continue
        if not has_mtllib and not inserted_mtllib:
            out.insert(len(out) - 1, f"mtllib {mtl_name}")
            inserted_mtllib = True
        if line.startswith("g ") and not has_usemtl and not inserted_usemtl:
            out.append(f"usemtl {MATERIAL_NAME}")
            inserted_usemtl = True
        elif line.startswith("usemtl "):
            if not inserted_usemtl:
                out[-1] = f"usemtl {MATERIAL_NAME}"
                inserted_usemtl = True
    obj.write_text("\n".join(out) + "\n", encoding="utf-8")


def write_pbr_mtl(obj: Path, albedo: Path, roughness: Path, normal: Path) -> Path:
    mtl = obj.with_suffix(".mtl")
    rel_albedo = Path("../textures") / albedo.name
    rel_roughness = Path("../textures") / roughness.name
    rel_normal = Path("../textures") / normal.name
    with mtl.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# PBR material generated by DG Face Pipeline\n")
        fh.write(f"newmtl {MATERIAL_NAME}\n")
        fh.write("Ka 0.000000 0.000000 0.000000\n")
        fh.write("Kd 1.000000 1.000000 1.000000\n")
        fh.write("Ks 0.120000 0.120000 0.120000\n")
        fh.write("Ns 16.000000\n")
        fh.write("illum 2\n")
        fh.write(f"map_Kd {rel_albedo.as_posix()}\n")
        fh.write(f"map_Pr {rel_roughness.as_posix()}\n")
        fh.write(f"norm {rel_normal.as_posix()}\n")
        fh.write(f"map_Bump -bm 0.12 {rel_normal.as_posix()}\n")
    ensure_obj_material(obj, mtl.name)
    return mtl


def default_photo(subject: str) -> Path:
    nested = EXAMPLES_DIR / subject / "ref.png"
    if nested.exists():
        return nested
    return EXAMPLES_DIR / f"{subject}_ref.png"


def parse_args(argv: List[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate JPG albedo, roughness, and normal maps.")
    parser.add_argument("--subject", default="winona")
    parser.add_argument("--photo", type=Path, default=None)
    return parser.parse_args(argv)


def main(argv: List[str] | None = None) -> int:
    args = parse_args(argv)
    photo = args.photo or default_photo(args.subject)
    root = OUTPUTS_DIR / "characters" / args.subject
    textures = root / "textures"
    try:
        albedo, roughness, normal = build_maps(photo, textures, args.subject)
        for obj in [
            root / "data" / f"{args.subject}_face_mesh.obj",
            root / "data" / f"{args.subject}_mediapipe_raw.obj",
            root / "maya" / f"{args.subject}_face_mesh_maya_cm.obj",
        ]:
            if obj.exists():
                write_pbr_mtl(obj, albedo, roughness, normal)
    except (FileNotFoundError, IOError, ValueError) as exc:
        log.error("Texture generation failed: %s", exc)
        return 1

    log.info("Wrote albedo: %s", albedo)
    log.info("Wrote roughness: %s", roughness)
    log.info("Wrote normal: %s", normal)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
