# File: C:\AI\apps\Makehuman\dg_face_pipeline\learned_face_mesh.py
# Repo: makehumancommunity/makehuman  Branch: feat/face-proportion-pipeline
# Orchestrator: DG_Brain
"""
Photo -> face mesh via a learned 3DMM-style reconstructor
=========================================================
Uses MediaPipe FaceMesh's 478 3D landmarks (a learned face-shape network --
not a generic landmark detector, it predicts per-vertex 3D position from
image content) combined with the canonical face model's triangulation to
produce a Wavefront OBJ mesh of the subject's face directly from a photo.

This bypasses the MakeHuman modifier pipeline entirely. The output mesh
has 478 verts (face-only, no scalp/neck) which is sparser than FLAME's
~5000 or MICA's full head, but it ships zero install friction (we already
have MediaPipe + OpenCV from the analyzer step), no FLAME license required,
and no GPU dependency.

A subsequent step can fit MakeHuman modifier values to this mesh by
optimization (non-rigid ICP) when MH-topology output is needed downstream.

Run:
    python C:\\AI\\apps\\Makehuman\\dg_face_pipeline\\learned_face_mesh.py ^
        --image C:\\AI\\apps\\DG_Brain\\assets\\refs\\winona_ref.png ^
        --out   C:\\AI\\apps\\DG_Brain\\data\\winona_face_mesh.obj
"""
from __future__ import annotations

import argparse
import logging
import re
import shutil
import sys
from pathlib import Path
from typing import List

import cv2
import mediapipe as mp
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("learned_face_mesh")

PIPELINE_DIR = Path(__file__).resolve().parent
EXAMPLES_DIR = PIPELINE_DIR / "examples"
OUTPUTS_DIR = PIPELINE_DIR / "outputs"
CANONICAL_OBJ = PIPELINE_DIR / "canonical_face_model.obj"
DEFAULT_MATERIAL_NAME = "face_photo_mat"


def copy_texture_for_obj(image_path: Path, out_obj: Path) -> Path:
    texture = out_obj.with_name(f"{out_obj.stem}_texture{image_path.suffix.lower()}")
    if image_path.resolve() != texture.resolve():
        shutil.copy2(image_path, texture)
    return texture


def write_mtl_for_obj(out_obj: Path, texture: Path, material_name: str = DEFAULT_MATERIAL_NAME) -> Path:
    mtl = out_obj.with_suffix(".mtl")
    texture_ref = texture.name
    with mtl.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Material generated by DG Face Pipeline\n")
        fh.write(f"newmtl {material_name}\n")
        fh.write("Ka 0.000000 0.000000 0.000000\n")
        fh.write("Kd 1.000000 1.000000 1.000000\n")
        fh.write("Ks 0.120000 0.120000 0.120000\n")
        fh.write("Ns 16.000000\n")
        fh.write("illum 2\n")
        fh.write(f"map_Kd {texture_ref}\n")
    return mtl


# -----------------------------------------------------------------------------
# Canonical topology loader
# -----------------------------------------------------------------------------
def load_canonical_faces(obj_path: Path) -> List[List[int]]:
    """Parse polygon vertex indices from a canonical face OBJ.

    OBJ faces may appear as "v", "v/vt", or "v/vt/vn"; we only need the v
    component because runtime UVs come from MediaPipe image coordinates. Indices
    are converted from 1-based (OBJ convention) to 0-based. Crucially, quads are
    preserved for Catmull-Clark tests instead of being fan-triangulated.
    """
    face_re = re.compile(r"^f\s+")
    faces: List[List[int]] = []
    with obj_path.open("r", encoding="utf-8") as fh:
        for line in fh:
            if not face_re.match(line):
                continue
            parts = line.split()[1:]
            idx = [int(p.split("/")[0]) - 1 for p in parts]
            if len(idx) >= 3:
                faces.append(idx)
    return faces


def triangulate_faces(faces: List[List[int]]) -> np.ndarray:
    """Fan-triangulate arbitrary polygon faces for the old midpoint subdivider."""
    tris: List[List[int]] = []
    for idx in faces:
        if len(idx) == 3:
            tris.append(idx)
        else:
            for i in range(1, len(idx) - 1):
                tris.append([idx[0], idx[i], idx[i + 1]])
    return np.asarray(tris, dtype=np.int64)


# -----------------------------------------------------------------------------
# Midpoint subdivision (densification)
# -----------------------------------------------------------------------------
def subdivide_once(
    verts: np.ndarray, uvs: np.ndarray, tris: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """One pass of midpoint subdivision -- every triangle becomes 4.

    Vertex positions interpolate linearly between the parent triangle's
    corners; same for UVs (which is the right thing for projective texture).
    Edges shared between triangles get a single shared midpoint so the mesh
    stays watertight.
    """
    new_verts: List[List[float]] = [list(v) for v in verts]
    new_uvs: List[List[float]] = [list(u) for u in uvs] if len(uvs) else []
    midpoint_cache: dict[tuple[int, int], int] = {}

    def get_midpoint(i: int, j: int) -> int:
        key = (min(i, j), max(i, j))
        cached = midpoint_cache.get(key)
        if cached is not None:
            return cached
        mid_v = ((verts[i] + verts[j]) / 2.0).tolist()
        new_verts.append(mid_v)
        if len(uvs):
            new_uvs.append(((uvs[i] + uvs[j]) / 2.0).tolist())
        idx = len(new_verts) - 1
        midpoint_cache[key] = idx
        return idx

    new_tris: List[List[int]] = []
    for tri in tris:
        v0, v1, v2 = int(tri[0]), int(tri[1]), int(tri[2])
        m01 = get_midpoint(v0, v1)
        m12 = get_midpoint(v1, v2)
        m20 = get_midpoint(v2, v0)
        new_tris.append([v0, m01, m20])
        new_tris.append([m01, v1, m12])
        new_tris.append([m20, m12, v2])
        new_tris.append([m01, m12, m20])

    return (
        np.asarray(new_verts, dtype=np.float64),
        np.asarray(new_uvs, dtype=np.float64) if new_uvs else np.empty((0, 2)),
        np.asarray(new_tris, dtype=np.int64),
    )


def subdivide_n(
    verts: np.ndarray, uvs: np.ndarray, tris: np.ndarray, n: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    for level in range(n):
        verts, uvs, tris = subdivide_once(verts, uvs, tris)
        log.info(
            "Subdivision pass %d/%d -> %d verts, %d triangles",
            level + 1, n, len(verts), len(tris),
        )
    return verts, uvs, tris


# -----------------------------------------------------------------------------
# Reconstruction
# -----------------------------------------------------------------------------
def reconstruct(
    image_path: Path,
    out_obj: Path,
    subdivisions: int = 0,
    canonical_obj: Path = CANONICAL_OBJ,
) -> Path:
    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")
    if not canonical_obj.exists():
        raise FileNotFoundError(f"Canonical face model missing: {canonical_obj}")

    img_bgr = cv2.imread(str(image_path))
    if img_bgr is None:
        raise IOError(f"OpenCV could not decode: {image_path}")
    h, w = img_bgr.shape[:2]
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    with mp.solutions.face_mesh.FaceMesh(
        static_image_mode=True,
        max_num_faces=1,
        refine_landmarks=True,
        min_detection_confidence=0.5,
    ) as fm:
        result = fm.process(img_rgb)
    if not result.multi_face_landmarks:
        raise RuntimeError("FaceMesh found no face in image")

    lms = result.multi_face_landmarks[0].landmark
    # MediaPipe lm.x, lm.y are in [0,1] normalized image coords (y-down).
    # lm.z is roughly in the same scale as lm.x (relative depth, negative
    # toward camera for the canonical model orientation).
    #
    # Flip y so the OBJ is y-up (matches our renderer's MakeHuman convention)
    # and scale by image width so x/y/z are in commensurate units.
    verts = np.array(
        [[lm.x * w, (1.0 - lm.y) * h, -lm.z * w] for lm in lms],
        dtype=np.float64,
    )
    log.info("Reconstructed %d landmark verts from FaceMesh", len(verts))

    faces = load_canonical_faces(canonical_obj)
    face_sizes: dict[int, int] = {}
    for face in faces:
        face_sizes[len(face)] = face_sizes.get(len(face), 0) + 1
    log.info("Loaded %d canonical faces from %s (%s)", len(faces), canonical_obj.name, face_sizes)

    max_face_idx = max(max(face) for face in faces)
    if max_face_idx >= len(verts):
        raise RuntimeError(
            f"Canonical topology references vertex {max_face_idx} but only "
            f"{len(verts)} predicted from FaceMesh"
        )

    # UV coordinates come for free: each landmark's normalized image (x, y) is
    # its UV. We flip v so OBJ convention (origin bottom-left) lines up with
    # MediaPipe convention (origin top-left). Vertex index == UV index, so the
    # face references will be of the form "f v/v v/v v/v".
    uvs = np.array([[lm.x, 1.0 - lm.y] for lm in lms], dtype=np.float64)
    active_vert_count = max_face_idx + 1
    if active_vert_count < len(verts):
        log.info(
            "Canonical topology uses %d/%d FaceMesh landmarks; trimming unused trailing verts",
            active_vert_count, len(verts),
        )
        verts = verts[:active_vert_count]
        uvs = uvs[:active_vert_count]

    if subdivisions > 0:
        if any(len(face) != 3 for face in faces):
            log.warning(
                "Canonical topology contains non-triangle faces; fan-triangulating "
                "before midpoint subdivision. Use --subdivisions 0 to preserve quads "
                "for Catmull-Clark in Maya."
            )
        tris = triangulate_faces(faces)
        verts, uvs, tris = subdivide_n(verts, uvs, tris, subdivisions)
        faces = tris.tolist()

    out_obj.parent.mkdir(parents=True, exist_ok=True)
    texture = copy_texture_for_obj(image_path, out_obj)
    mtl = write_mtl_for_obj(out_obj, texture)
    with out_obj.open("w", encoding="utf-8") as fh:
        fh.write("# Face mesh reconstructed via MediaPipe FaceMesh\n")
        fh.write(f"# Source image: {image_path}\n")
        fh.write(f"# Canonical topology: {canonical_obj}\n")
        fh.write(f"# Image size: {w} x {h}\n")
        fh.write(f"# Verts: {len(verts)}  UVs: {len(uvs)}  Faces: {len(faces)}\n")
        fh.write(f"mtllib {mtl.name}\n")
        fh.write("g face_mesh\n")
        fh.write(f"usemtl {DEFAULT_MATERIAL_NAME}\n")
        for v in verts:
            fh.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        for uv in uvs:
            fh.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        for face in faces:
            # Vertex index == UV index for this mesh (1-indexed in OBJ).
            parts = [f"{idx + 1}/{idx + 1}" for idx in face]
            fh.write("f " + " ".join(parts) + "\n")
    log.info("Wrote face mesh OBJ: %s (verts+UVs)", out_obj)
    return out_obj


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------
def parse_args(argv: List[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Reconstruct a face OBJ mesh from a photo via MediaPipe FaceMesh.",
    )
    parser.add_argument(
        "--image",
        type=Path,
        default=EXAMPLES_DIR / "winona_ref.png",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUTPUTS_DIR / "data" / "subject_face_mesh.obj",
    )
    parser.add_argument(
        "--subdivisions",
        type=int,
        default=0,
        help=(
            "Number of midpoint-subdivision passes. Each pass quadruples the "
            "triangle count and reduces texture-sampling facets. 0 (default) "
            "keeps the raw 478-vert canonical mesh; 2 -> ~7600 verts, 14336 "
            "triangles -- visibly smoother texture and still <1s to render."
        ),
    )
    parser.add_argument(
        "--canonical",
        type=Path,
        default=CANONICAL_OBJ,
        help=(
            "Canonical topology OBJ to reuse. Defaults to Google's triangulated "
            "MediaPipe canonical_face_model.obj. Pass canonical_face_model_v002.obj "
            "to preserve the local quad-dominant topology."
        ),
    )
    return parser.parse_args(argv)


def main(argv: List[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        reconstruct(
            args.image,
            args.out,
            subdivisions=args.subdivisions,
            canonical_obj=args.canonical,
        )
    except FileNotFoundError as exc:
        log.error("Missing input: %s", exc)
        return 2
    except (RuntimeError, ValueError, IOError) as exc:
        log.error("Reconstruction failed: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
